name: test-build-deploy
on: push
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: solutiontest/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
